language: r
sudo: false
cache: packages
latex: false

r:
  - release
  - devel

r_github_packages:
  - statnet/network
  - statnet/ergm
  - statnet/tergm

warnings_are_errors: true

notifications:
  email: false
  slack: epimodel:iY6F3MeHlZ2LCM4MwuVRJj7D
